using System.Diagnostics;
using System.Reflection;
using System.Text;
using Microsoft.Extensions.DependencyInjection;
using System.CommandLine;
using TinyCity.BookmarkEngines;
using TinyCity.Commands;
using TinyCity.Commands.Settings;

namespace TinyCity
{
    public class Program
    {
        async static Task<int> Main(string[] args)
        {
            EnsureDownloadedBackupIsRemoved();
            Console.OutputEncoding = Encoding.UTF8; // emoji support

            var stopWatch = Stopwatch.StartNew();
            var interceptor = new ExtraInfoInterceptor();
            Exception? capturedException = null;

            var services = SetupIoC();
            var serviceProvider = services.BuildServiceProvider();

            var rootCommand = new RootCommand("A command line tool for searching bookmarks");
            
            var searchCommand = SearchCommand.CreateCommand(serviceProvider, interceptor, ex => capturedException = ex);
            var listCommand = ListCommand.CreateCommand(serviceProvider, interceptor, ex => capturedException = ex);
            var updateCommand = UpdateCommand.CreateCommand(serviceProvider, interceptor, ex => capturedException = ex);
            var configCommand = ConfigCommand.CreateCommand(serviceProvider, interceptor, ex => capturedException = ex);

            rootCommand.AddCommand(searchCommand);
            rootCommand.AddCommand(listCommand);
            rootCommand.AddCommand(updateCommand);
            rootCommand.AddCommand(configCommand);

            int result = await rootCommand.InvokeAsync(args);
            
            stopWatch.Stop();
            interceptor.ShowOutput(stopWatch, capturedException);
            
            return result;
        }

        static string GetVersion()
        {
            // Generated by GitVersion in its msbuild task, from the Git tag.
            return Assembly.GetExecutingAssembly().GetName().Version?.ToString() ?? "0.0.1";
        }

        static ServiceCollection SetupIoC()
        {
            var settings = TinyCitySettings.Load();

            var services = new ServiceCollection();
            services.AddSingleton<ChromeBookmarks>();
            services.AddSingleton<MarkdownBookmarks>();
            services.AddSingleton<HtmlBookmarks>();
            services.AddSingleton<BookmarkAggregator>();
            services.AddSingleton<TinyCitySettings>(settings);
            services.AddSingleton<ConfigCommand>();
            services.AddSingleton<SearchCommand>();
            services.AddSingleton<ListCommand>();
            services.AddSingleton<UpdateCommand>();

            return services;
        }

        static void EnsureDownloadedBackupIsRemoved()
        {
            string backupFilename = $"{Environment.ProcessPath}.bak";
            if (Path.Exists(backupFilename))
            {
                File.Delete(backupFilename);
            }
        }
    }
}